Milestone 1: Mobile Version Portfolio
Dinma-Faith/Mobile-Version-Skelenton-Portfolio pull request #1
Opened 2022-02-15 11:33 UTC by Dinma-Faith

##Mobile View of Portfolio:

In this milestone I; 
-Created HTML and CSS file
-Created Img file and added images in it 
-Created a linters file to detect code errors

2022-02-15 15:18 UTC, Amrhub requested changes
Hi @Dinma-Faith,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## To Highlight ✔️ 
Professional documentation ✔️ 
Clean code ✔️ 

## Required Changes ♻️
_Check the comments under the review._

Most of the changes required have to do with following the Figma design, other than that you have made a great effort and fantastic work

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 15:18 UTC, Amrhub commented on style.css
> +}
- [ ] Let's make sure our background image is on the `headline` section i.e `header` excluded to match the design, if you notice in Figma design back ground image starts after the navbar/header tag

Your Implementation | Figma design 
:-----:|:-----:
![image](https://user-images.githubusercontent.com/87689547/154088214-802e4114-0338-4c46-a2fd-51b690eea341.png) | ![image](https://user-images.githubusercontent.com/87689547/154087955-2d2ca547-325e-47ae-8a51-d7ecc2115137.png)

2022-02-15 15:18 UTC, Amrhub commented on style.css
> +}
- [ ] Let's make sure we don't have margins to the top to match design the space in the design to the top is (I know can be confusing) just there to memic as this website was opened via mobile

Your implementation | Figma Design
:------:|:-----:
![image](https://user-images.githubusercontent.com/87689547/154088886-2f53acdd-6989-4c0c-ab31-87273c3ae97b.png) | ![image](https://user-images.githubusercontent.com/87689547/154089093-5d34e4fc-d712-4a13-9506-e3d522dfedf8.png)

2022-02-15 15:18 UTC, Amrhub commented on style.css
> +  margin-left: 1rem;
- [ ] In order to match Figma design we need to make sure that our `let's connect doesn't have any margin left so it starts with the rest of the content on this page.
I made a red straight line to show you how it should be aligned in comparison with Figma design

Your implementation | Figma Design
:------:|:-----:
![image](https://user-images.githubusercontent.com/87689547/154089759-0bf77b46-a84e-4cd2-9443-f4eeb3b09ac5.png) | ![image](https://user-images.githubusercontent.com/87689547/154090900-f2a627e7-28aa-4b0a-afe0-ca2dbbe1efd7.png)

2022-02-15 15:18 UTC, Amrhub commented on style.css
> +  margin: 0.5rem;
- [ ] As previously mentioned above, Let's make sure our social media links starts with the start of the rest of content

Your implementation | Figma Design
:------:|:-----:
![image](https://user-images.githubusercontent.com/87689547/154090472-22c30473-7ff6-4cdd-b0eb-5d123c632795.png) | ![image](https://user-images.githubusercontent.com/87689547/154090854-d0efe3fa-76d3-492e-ae49-51e62c2902a2.png)

2022-02-16 09:41 UTC, ReshyResh approved these changes
# Hi @Dinma-Faith , 

### Good job addressing the changes requested by the previous reviewer!
Your project is complete fow now, but keep in mind that, as the other reviewer said, you should avoid hard-coded values for the width of the website, as later on you will be tasked with making it responsive for desktop screens as well!  

#### There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-16 09:59 UTC, merged